name: CD

on:
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Write file
        uses: DamianReeves/write-file-action@master
        with:
          path: test.txt
          contents: |
            Hello World!
          write-mode: overwrite
        
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/decatur-robotics/gearbox:latest
          outputs: type=docker,dest=/tmp/gearbox.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gearbox
          path: /tmp/gearbox.tar

  push_to_ghcr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gearbox
          path: /tmp
      
      - name: Load image
        run: |
          docker load --input /tmp/gearbox.tar
          docker image ls -a

      - name: Sign in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u decatur-robotics --password-stdin

      - name: Push to GHCR
        run: docker push ghcr.io/decatur-robotics/gearbox:latest