name: CD

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ROLLBAR_ACCESS_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notify deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.2
        id: rollbar_pre_deploy
        with:
          environment: "production"
          version: ${{ github.sha }}
          status: "started"
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: ${{ github.actor }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gearbox
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/gearbox.tar
          docker image ls -a

      - name: Sign in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u decatur-robotics --password-stdin

      - name: Push to GHCR
        run: docker push ghcr.io/decatur-robotics/gearbox:latest

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Configure AWS
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-1

      - name: Deploy to ECS
        run: aws ecs update-service --cluster gearbox --service gearbox --force-new-deployment

      - name: Notify finish deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.2
        id: rollbar_post_deploy
        with:
          environment: "production"
          version: ${{ github.sha }}
          status: "succeeded"
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: ${{ github.actor }}
          DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}
