name: Push to GHCR

on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - main
    types:
      - completed
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gearbox
          path: /tmp/gearbox.tar
      
      - name: Load image
        run: |
          docker load --input /tmp/gearbox.tar
          docker image ls -a